# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  hermesgatewayocelot:
    image: hermesgatewayocelot
    build:
      context: .
      dockerfile: src/Dockerfile
    ports:
      - 8000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8000
    volumes:
      - ~/.vsdbg:c:\remote_debugger:rw
